name: Push Docker to GHCR

# 触发条件：推送到 master 分支时执行
on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # 授予推送镜像到 GHCR 的权限
      contents: read   # 授予读取代码的权限

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 用户名即 GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的令牌，无需手动配置

      - name: 提取镜像标签
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/math-api  # 镜像名格式：ghcr.io/用户名/项目名
          tags: |
            type=sha,format=short  # 用 commit SHA 作为标签（短格式）
            type=ref,event=branch  # 用分支名作为标签（如 master）
            type=semver,pattern={{version}},from=package.json  # 从 package.json 提取版本号作为标签

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        with:
          context: .  # 构建上下文为项目根目录
          push: true  # 推送镜像
          tags: ${{ steps.meta.outputs.tags }}  # 使用上面生成的标签
          cache-from: type=gha  # 使用 GitHub Actions 缓存加速构建
          cache-to: type=gha,mode=max
